FROM 		tomcat:9.0-jre8-alpine

MAINTAINER 	Natasha (nifty.natasha@gmail.com)

COPY		conf/tomcat-users.xml  /usr/local/Cellar/tomcat/8.5.20/libexec/conf
COPY 		target/hello-world-war-1.0.0.war /usr/local/Cellar/tomcat/8.5.20/libexec/webapps
